# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
workflows:
  main:
    jobs:
      - test

jobs:
  test:
    macos:
      xcode: "12.2"
    resource_class: macos.x86.metal.gen1
    steps:
      - run: echo "im a machine provisioned job"
      - run: uname -a
